//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 06:44:12 PM IST 
//


package com.ats.property.dto;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for advertisementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="advertisementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="planId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="propertyForTypeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="propertyTypeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="builderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildupArea" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="buildupAreaUnitId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="bedRoomId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="bathRoomId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="furnishedStatusId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="balconyId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="propertyOnFloorId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="totalFloor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="expectedPrice" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="maintenanceCharges" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="maintenancePeriodId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="securityDeposit" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="responseFromBrokers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="projectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="propertyFeatures" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isTermsAgreed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="galleryImage" type="{}galleryImageType" maxOccurs="unbounded"/>
 *         &lt;element name="propertyAmenities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="possessionStatusId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="possessionOrAgeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="moreProperty" type="{}morePropertyType" maxOccurs="unbounded"/>
 *         &lt;element name="imageTypeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="propertyAmenitiesMap" type="{}amenitiesByCategory"/>
 *         &lt;element name="galleryImageByImageTypeMap" type="{}galleryImagesByImageType"/>
 *         &lt;element name="propertyLogo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyLogo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bedRooms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildupAreaName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildupAreaRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="possession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="overviewBannerImages" type="{}galleryImageType" maxOccurs="unbounded"/>
 *         &lt;element name="propertyForTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="propertyTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isApproved" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "advertisementType", propOrder = {
    "id",
    "planId",
    "propertyForTypeId",
    "propertyTypeId",
    "locationId",
    "address",
    "builderName",
    "buildupArea",
    "buildupAreaUnitId",
    "bedRoomId",
    "bathRoomId",
    "furnishedStatusId",
    "balconyId",
    "propertyOnFloorId",
    "totalFloor",
    "expectedPrice",
    "maintenanceCharges",
    "maintenancePeriodId",
    "securityDeposit",
    "responseFromBrokers",
    "projectName",
    "description",
    "propertyFeatures",
    "isTermsAgreed",
    "galleryImage",
    "propertyAmenities",
    "possessionStatusId",
    "possessionOrAgeId",
    "moreProperty",
    "imageTypeId",
    "propertyAmenitiesMap",
    "galleryImageByImageTypeMap",
    "propertyLogo",
    "companyLogo",
    "companyName",
    "locationName",
    "bedRooms",
    "buildupAreaName",
    "cost",
    "buildupAreaRange",
    "priceRange",
    "possession",
    "overviewBannerImages",
    "propertyForTypeName",
    "propertyTypeName",
    "isApproved"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
public class AdvertisementType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long id;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long planId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long propertyForTypeId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long propertyTypeId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long locationId;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String address;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String builderName;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Double buildupArea;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long buildupAreaUnitId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long bedRoomId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long bathRoomId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long furnishedStatusId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long balconyId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long propertyOnFloorId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long totalFloor;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long expectedPrice;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long maintenanceCharges;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long maintenancePeriodId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long securityDeposit;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String responseFromBrokers;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String projectName;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String description;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String propertyFeatures;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String isTermsAgreed;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected List<GalleryImageType> galleryImage;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String propertyAmenities;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long possessionStatusId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long possessionOrAgeId;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected List<MorePropertyType> moreProperty;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long imageTypeId;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected HashMap propertyAmenitiesMap;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected HashMap galleryImageByImageTypeMap;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String propertyLogo;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String companyLogo;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String companyName;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String locationName;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String bedRooms;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String buildupAreaName;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String cost;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String buildupAreaRange;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String priceRange;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String possession;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected List<GalleryImageType> overviewBannerImages;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String propertyForTypeName;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String propertyTypeName;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected boolean isApproved;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the planId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getPlanId() {
        return planId;
    }

    /**
     * Sets the value of the planId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPlanId(Long value) {
        this.planId = value;
    }

    /**
     * Gets the value of the propertyForTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getPropertyForTypeId() {
        return propertyForTypeId;
    }

    /**
     * Sets the value of the propertyForTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyForTypeId(Long value) {
        this.propertyForTypeId = value;
    }

    /**
     * Gets the value of the propertyTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getPropertyTypeId() {
        return propertyTypeId;
    }

    /**
     * Sets the value of the propertyTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyTypeId(Long value) {
        this.propertyTypeId = value;
    }

    /**
     * Gets the value of the locationId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setLocationId(Long value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the builderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getBuilderName() {
        return builderName;
    }

    /**
     * Sets the value of the builderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBuilderName(String value) {
        this.builderName = value;
    }

    /**
     * Gets the value of the buildupArea property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Double getBuildupArea() {
        return buildupArea;
    }

    /**
     * Sets the value of the buildupArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBuildupArea(Double value) {
        this.buildupArea = value;
    }

    /**
     * Gets the value of the buildupAreaUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getBuildupAreaUnitId() {
        return buildupAreaUnitId;
    }

    /**
     * Sets the value of the buildupAreaUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBuildupAreaUnitId(Long value) {
        this.buildupAreaUnitId = value;
    }

    /**
     * Gets the value of the bedRoomId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getBedRoomId() {
        return bedRoomId;
    }

    /**
     * Sets the value of the bedRoomId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBedRoomId(Long value) {
        this.bedRoomId = value;
    }

    /**
     * Gets the value of the bathRoomId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getBathRoomId() {
        return bathRoomId;
    }

    /**
     * Sets the value of the bathRoomId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBathRoomId(Long value) {
        this.bathRoomId = value;
    }

    /**
     * Gets the value of the furnishedStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getFurnishedStatusId() {
        return furnishedStatusId;
    }

    /**
     * Sets the value of the furnishedStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setFurnishedStatusId(Long value) {
        this.furnishedStatusId = value;
    }

    /**
     * Gets the value of the balconyId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getBalconyId() {
        return balconyId;
    }

    /**
     * Sets the value of the balconyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBalconyId(Long value) {
        this.balconyId = value;
    }

    /**
     * Gets the value of the propertyOnFloorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getPropertyOnFloorId() {
        return propertyOnFloorId;
    }

    /**
     * Sets the value of the propertyOnFloorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyOnFloorId(Long value) {
        this.propertyOnFloorId = value;
    }

    /**
     * Gets the value of the totalFloor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getTotalFloor() {
        return totalFloor;
    }

    /**
     * Sets the value of the totalFloor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setTotalFloor(Long value) {
        this.totalFloor = value;
    }

    /**
     * Gets the value of the expectedPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getExpectedPrice() {
        return expectedPrice;
    }

    /**
     * Sets the value of the expectedPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setExpectedPrice(Long value) {
        this.expectedPrice = value;
    }

    /**
     * Gets the value of the maintenanceCharges property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getMaintenanceCharges() {
        return maintenanceCharges;
    }

    /**
     * Sets the value of the maintenanceCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setMaintenanceCharges(Long value) {
        this.maintenanceCharges = value;
    }

    /**
     * Gets the value of the maintenancePeriodId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getMaintenancePeriodId() {
        return maintenancePeriodId;
    }

    /**
     * Sets the value of the maintenancePeriodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setMaintenancePeriodId(Long value) {
        this.maintenancePeriodId = value;
    }

    /**
     * Gets the value of the securityDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getSecurityDeposit() {
        return securityDeposit;
    }

    /**
     * Sets the value of the securityDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setSecurityDeposit(Long value) {
        this.securityDeposit = value;
    }

    /**
     * Gets the value of the responseFromBrokers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getResponseFromBrokers() {
        return responseFromBrokers;
    }

    /**
     * Sets the value of the responseFromBrokers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setResponseFromBrokers(String value) {
        this.responseFromBrokers = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the propertyFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPropertyFeatures() {
        return propertyFeatures;
    }

    /**
     * Sets the value of the propertyFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyFeatures(String value) {
        this.propertyFeatures = value;
    }

    /**
     * Gets the value of the isTermsAgreed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getIsTermsAgreed() {
        return isTermsAgreed;
    }

    /**
     * Sets the value of the isTermsAgreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setIsTermsAgreed(String value) {
        this.isTermsAgreed = value;
    }

    /**
     * Gets the value of the galleryImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the galleryImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGalleryImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GalleryImageType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public List<GalleryImageType> getGalleryImage() {
        if (galleryImage == null) {
            galleryImage = new ArrayList<GalleryImageType>();
        }
        return this.galleryImage;
    }

    /**
     * Gets the value of the propertyAmenities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPropertyAmenities() {
        return propertyAmenities;
    }

    /**
     * Sets the value of the propertyAmenities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyAmenities(String value) {
        this.propertyAmenities = value;
    }

    /**
     * Gets the value of the possessionStatusId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getPossessionStatusId() {
        return possessionStatusId;
    }

    /**
     * Sets the value of the possessionStatusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPossessionStatusId(Long value) {
        this.possessionStatusId = value;
    }

    /**
     * Gets the value of the possessionOrAgeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getPossessionOrAgeId() {
        return possessionOrAgeId;
    }

    /**
     * Sets the value of the possessionOrAgeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPossessionOrAgeId(Long value) {
        this.possessionOrAgeId = value;
    }

    /**
     * Gets the value of the moreProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moreProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoreProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MorePropertyType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public List<MorePropertyType> getMoreProperty() {
        if (moreProperty == null) {
            moreProperty = new ArrayList<MorePropertyType>();
        }
        return this.moreProperty;
    }

    /**
     * Gets the value of the imageTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getImageTypeId() {
        return imageTypeId;
    }

    /**
     * Sets the value of the imageTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setImageTypeId(Long value) {
        this.imageTypeId = value;
    }

    /**
     * Gets the value of the propertyAmenitiesMap property.
     * 
     * @return
     *     possible object is
     *     {@link HashMap }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public HashMap getPropertyAmenitiesMap() {
        return propertyAmenitiesMap;
    }

    /**
     * Sets the value of the propertyAmenitiesMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashMap }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyAmenitiesMap(HashMap value) {
        this.propertyAmenitiesMap = value;
    }

    /**
     * Gets the value of the galleryImageByImageTypeMap property.
     * 
     * @return
     *     possible object is
     *     {@link HashMap }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public HashMap getGalleryImageByImageTypeMap() {
        return galleryImageByImageTypeMap;
    }

    /**
     * Sets the value of the galleryImageByImageTypeMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashMap }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setGalleryImageByImageTypeMap(HashMap value) {
        this.galleryImageByImageTypeMap = value;
    }

    /**
     * Gets the value of the propertyLogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPropertyLogo() {
        return propertyLogo;
    }

    /**
     * Sets the value of the propertyLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyLogo(String value) {
        this.propertyLogo = value;
    }

    /**
     * Gets the value of the companyLogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getCompanyLogo() {
        return companyLogo;
    }

    /**
     * Sets the value of the companyLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setCompanyLogo(String value) {
        this.companyLogo = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the locationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getLocationName() {
        return locationName;
    }

    /**
     * Sets the value of the locationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setLocationName(String value) {
        this.locationName = value;
    }

    /**
     * Gets the value of the bedRooms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getBedRooms() {
        return bedRooms;
    }

    /**
     * Sets the value of the bedRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBedRooms(String value) {
        this.bedRooms = value;
    }

    /**
     * Gets the value of the buildupAreaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getBuildupAreaName() {
        return buildupAreaName;
    }

    /**
     * Sets the value of the buildupAreaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBuildupAreaName(String value) {
        this.buildupAreaName = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setCost(String value) {
        this.cost = value;
    }

    /**
     * Gets the value of the buildupAreaRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getBuildupAreaRange() {
        return buildupAreaRange;
    }

    /**
     * Sets the value of the buildupAreaRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBuildupAreaRange(String value) {
        this.buildupAreaRange = value;
    }

    /**
     * Gets the value of the priceRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPriceRange() {
        return priceRange;
    }

    /**
     * Sets the value of the priceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPriceRange(String value) {
        this.priceRange = value;
    }

    /**
     * Gets the value of the possession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPossession() {
        return possession;
    }

    /**
     * Sets the value of the possession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPossession(String value) {
        this.possession = value;
    }

    /**
     * Gets the value of the overviewBannerImages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overviewBannerImages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverviewBannerImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GalleryImageType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public List<GalleryImageType> getOverviewBannerImages() {
        if (overviewBannerImages == null) {
            overviewBannerImages = new ArrayList<GalleryImageType>();
        }
        return this.overviewBannerImages;
    }

    /**
     * Gets the value of the propertyForTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPropertyForTypeName() {
        return propertyForTypeName;
    }

    /**
     * Sets the value of the propertyForTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyForTypeName(String value) {
        this.propertyForTypeName = value;
    }

    /**
     * Gets the value of the propertyTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPropertyTypeName() {
        return propertyTypeName;
    }

    /**
     * Sets the value of the propertyTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyTypeName(String value) {
        this.propertyTypeName = value;
    }

    /**
     * Gets the value of the isApproved property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public boolean isIsApproved() {
        return isApproved;
    }

    /**
     * Sets the value of the isApproved property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-26T06:44:12+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setIsApproved(boolean value) {
        this.isApproved = value;
    }

    public void setGalleryImage(List<GalleryImageType> value) {
        List<GalleryImageType> draftl = this.getGalleryImage();
        draftl.addAll(value);
    }

    public void setMoreProperty(List<MorePropertyType> value) {
        List<MorePropertyType> draftl = this.getMoreProperty();
        draftl.addAll(value);
    }

    public void setOverviewBannerImages(List<GalleryImageType> value) {
        List<GalleryImageType> draftl = this.getOverviewBannerImages();
        draftl.addAll(value);
    }

}
