//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 08:00:46 PM IST 
//


package com.ats.property.dto;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for budgetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="budgetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromlevel" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="tolevel" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="currencyVal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "budgetType", propOrder = {
    "id",
    "name",
    "fromlevel",
    "tolevel",
    "currencyVal"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
public class BudgetType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String name;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long fromlevel;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long tolevel;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String currencyVal;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the fromlevel property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getFromlevel() {
        return fromlevel;
    }

    /**
     * Sets the value of the fromlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setFromlevel(Long value) {
        this.fromlevel = value;
    }

    /**
     * Gets the value of the tolevel property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getTolevel() {
        return tolevel;
    }

    /**
     * Sets the value of the tolevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setTolevel(Long value) {
        this.tolevel = value;
    }

    /**
     * Gets the value of the currencyVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getCurrencyVal() {
        return currencyVal;
    }

    /**
     * Sets the value of the currencyVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-08-23T08:00:46+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setCurrencyVal(String value) {
        this.currencyVal = value;
    }

}
