//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 11:21:09 PM IST 
//


package com.ats.property.dto;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for galleryImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="galleryImageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="imageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imageTypeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "galleryImageType", propOrder = {
    "id",
    "imageName",
    "imageTypeId"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
public class GalleryImageType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String imageName;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long imageTypeId;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the imageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getImageName() {
        return imageName;
    }

    /**
     * Sets the value of the imageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setImageName(String value) {
        this.imageName = value;
    }

    /**
     * Gets the value of the imageTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getImageTypeId() {
        return imageTypeId;
    }

    /**
     * Sets the value of the imageTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-09-23T11:21:09+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setImageTypeId(Long value) {
        this.imageTypeId = value;
    }

}
