//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.10 at 11:46:05 PM IST 
//


package com.ats.property.dto;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nameDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nameDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="isPopular" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="bedrooms" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="bathrooms" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="floors" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="nameForPoster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nameForFinder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nameDataType", propOrder = {
    "id",
    "name",
    "type",
    "parentId",
    "isPopular",
    "bedrooms",
    "bathrooms",
    "floors",
    "nameForPoster",
    "nameForFinder",
    "label"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
public class NameDataType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String name;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String type;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long parentId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Byte isPopular;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long bedrooms;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long bathrooms;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long floors;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String nameForPoster;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String nameForFinder;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String label;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setParentId(Long value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the isPopular property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Byte getIsPopular() {
        return isPopular;
    }

    /**
     * Sets the value of the isPopular property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setIsPopular(Byte value) {
        this.isPopular = value;
    }

    /**
     * Gets the value of the bedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getBedrooms() {
        return bedrooms;
    }

    /**
     * Sets the value of the bedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBedrooms(Long value) {
        this.bedrooms = value;
    }

    /**
     * Gets the value of the bathrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getBathrooms() {
        return bathrooms;
    }

    /**
     * Sets the value of the bathrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBathrooms(Long value) {
        this.bathrooms = value;
    }

    /**
     * Gets the value of the floors property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getFloors() {
        return floors;
    }

    /**
     * Sets the value of the floors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setFloors(Long value) {
        this.floors = value;
    }

    /**
     * Gets the value of the nameForPoster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getNameForPoster() {
        return nameForPoster;
    }

    /**
     * Sets the value of the nameForPoster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setNameForPoster(String value) {
        this.nameForPoster = value;
    }

    /**
     * Gets the value of the nameForFinder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getNameForFinder() {
        return nameForFinder;
    }

    /**
     * Sets the value of the nameForFinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setNameForFinder(String value) {
        this.nameForFinder = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-10T11:46:05+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setLabel(String value) {
        this.label = value;
    }

}
