//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 03:26:25 PM IST 
//


package com.ats.property.dto;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="projectName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="galleryImage" type="{}galleryImageType" maxOccurs="unbounded"/>
 *         &lt;element name="propertyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bedRooms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startingPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="possession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchResultType", propOrder = {
    "id",
    "projectName",
    "galleryImage",
    "propertyType",
    "location",
    "bedRooms",
    "startingPrice",
    "possession",
    "description"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
public class SearchResultType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected Long id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String projectName;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected List<GalleryImageType> galleryImage;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String propertyType;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String location;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String bedRooms;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String startingPrice;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String possession;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    protected String description;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the galleryImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the galleryImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGalleryImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GalleryImageType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public List<GalleryImageType> getGalleryImage() {
        if (galleryImage == null) {
            galleryImage = new ArrayList<GalleryImageType>();
        }
        return this.galleryImage;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPropertyType(String value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the bedRooms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getBedRooms() {
        return bedRooms;
    }

    /**
     * Sets the value of the bedRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setBedRooms(String value) {
        this.bedRooms = value;
    }

    /**
     * Gets the value of the startingPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getStartingPrice() {
        return startingPrice;
    }

    /**
     * Sets the value of the startingPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setStartingPrice(String value) {
        this.startingPrice = value;
    }

    /**
     * Gets the value of the possession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getPossession() {
        return possession;
    }

    /**
     * Sets the value of the possession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setPossession(String value) {
        this.possession = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-10-13T03:26:25+05:30", comments = "JAXB RI vhudson-jaxb-ri-2.1-833")
    public void setDescription(String value) {
        this.description = value;
    }

    public void setGalleryImage(List<GalleryImageType> value) {
        List<GalleryImageType> draftl = this.getGalleryImage();
        draftl.addAll(value);
    }

}
