insert into City (name, stateId, isPopular) values ('Visakhapatnam', 1, 1);
insert into City (name, stateId, isPopular) values ('Vijayawada', 1, 1);
insert into City (name, stateId, isPopular) values ('Guntur', 1, 1);
insert into City (name, stateId, isPopular) values ('Nellore', 1, 1);
insert into City (name, stateId, isPopular) values ('Kurnool', 1, 1);
insert into City (name, stateId, isPopular) values ('Rajahmundry', 1, 1);
insert into City (name, stateId, isPopular) values ('Tirupati', 1, 1);
insert into City (name, stateId, isPopular) values ('Kadapa', 1, 1);
insert into City (name, stateId, isPopular) values ('Kakinada', 1, 1);
insert into City (name, stateId, isPopular) values ('Anantapur', 1, 1);
insert into City (name, stateId, isPopular) values ('Vizianagaram', 1, 1);
insert into City (name, stateId, isPopular) values ('Eluru West Godavari', 1, 1);
insert into City (name, stateId, isPopular) values ('Ongole	Prakasam', 1, 1);
insert into City (name, stateId, isPopular) values ('Nandyal	Kurnool', 1, 1);
insert into City (name, stateId, isPopular) values ('Machilipatnam', 1, 1);
insert into City (name, stateId, isPopular) values ('Adoni	Kurnool', 1, 1);
insert into City (name, stateId, isPopular) values ('Tenali	Guntur', 1, 1);
insert into City (name, stateId, isPopular) values ('Proddatur	Kadapa', 1, 1);
insert into City (name, stateId, isPopular) values ('Chittoor	', 1, 1);
insert into City (name, stateId, isPopular) values ('Hindupur', 1, 1);
insert into City (name, stateId, isPopular) values ('Bhimavaram', 1, 1);
insert into City (name, stateId, isPopular) values ('Madanapalle	Chittoor', 1, 1);
insert into City (name, stateId, isPopular) values ('Srikakulam', 1, 1);
insert into City (name, stateId, isPopular) values ('Guntakal', 1, 1);
insert into City (name, stateId, isPopular) values ('Dharmavaram', 1, 1);
insert into City (name, stateId, isPopular) values ('Gudivada', 1, 1);
insert into City (name, stateId, isPopular) values ('Narasaraopet', 1, 1);
insert into City (name, stateId, isPopular) values ('Tadpatri', 1, 1);
insert into City (name, stateId, isPopular) values ('Tadepalligudem', 1, 1);
insert into City (name, stateId, isPopular) values ('Amaravati', 1, 1);
insert into City (name, stateId, isPopular) values ('Chilakaluripet', 1, 1);

-- ---Assam----------



insert into City (name, stateId, isPopular) values ('Amguri', 3, 1);
insert into City (name, stateId, isPopular) values ('Amingaon', 3, 1);
insert into City (name, stateId, isPopular) values ('Badarpur', 3, 1);
insert into City (name, stateId, isPopular) values ('BajaliPath', 3, 1);
insert into City (name, stateId, isPopular) values ('BaksaMusa', 3, 1);
insert into City (name, stateId, isPopular) values ('Barpeta', 3, 1);
insert into City (name, stateId, isPopular) values ('Bhergaon', 3, 1);
insert into City (name, stateId, isPopular) values ('Bihpuria', 3, 1);
insert into City (name, stateId, isPopular) values ('Bijni', 3, 1);
insert into City (name, stateId, isPopular) values ('Bilasipara', 3, 1);
insert into City (name, stateId, isPopular) values ('Biswnath', 3, 1);
insert into City (name, stateId, isPopular) values ('Bokajan', 3, 1);
insert into City (name, stateId, isPopular) values ('Bokakhat', 3, 1);
insert into City (name, stateId, isPopular) values ('Bongaigaon', 3, 1);
insert into City (name, stateId, isPopular) values ('Borpathar', 3, 1);
insert into City (name, stateId, isPopular) values ('Cachar', 3, 1);
insert into City (name, stateId, isPopular) values ('Chabua', 3, 1);
insert into City (name, stateId, isPopular) values ('Chapar', 3, 1);
insert into City (name, stateId, isPopular) values ('Charaideo', 3, 1);
insert into City (name, stateId, isPopular) values ('ChirangBasu', 3, 1);
insert into City (name, stateId, isPopular) values ('Dansiri', 3, 1);
insert into City (name, stateId, isPopular) values ('DarrangMang', 3, 1);
insert into City (name, stateId, isPopular) values ('Dergaon', 3, 1);
insert into City (name, stateId, isPopular) values ('Dhakuakhona', 3, 1);
insert into City (name, stateId, isPopular) values ('Dhekiajuli', 3, 1);
insert into City (name, stateId, isPopular) values ('Dhemaji', 3, 1);
insert into City (name, stateId, isPopular) values ('Dhubri', 3, 1);
insert into City (name, stateId, isPopular) values ('Dibrugarh', 3, 1);
insert into City (name, stateId, isPopular) values ('Digboi', 3, 1);
insert into City (name, stateId, isPopular) values ('Dima Hasao', 3, 1);
insert into City (name, stateId, isPopular) values ('Doboka', 3, 1);
insert into City (name, stateId, isPopular) values ('Dokmoka', 3, 1);
insert into City (name, stateId, isPopular) values ('Donkamokam', 3, 1);
insert into City (name, stateId, isPopular) values ('Doomdooma', 3, 1);
insert into City (name, stateId, isPopular) values ('Duni', 3, 1);
insert into City (name, stateId, isPopular) values ('Goalpara', 3, 1);
insert into City (name, stateId, isPopular) values ('Gohpur', 3, 1);
insert into City (name, stateId, isPopular) values ('Golaghat', 3, 1);
insert into City (name, stateId, isPopular) values ('Gossaigaon', 3, 1);
insert into City (name, stateId, isPopular) values ('Gouripur', 3, 1);
insert into City (name, stateId, isPopular) values ('Hailakandi', 3, 1);
insert into City (name, stateId, isPopular) values ('Hamren', 3, 1);
insert into City (name, stateId, isPopular) values ('Hojai', 3, 1);
insert into City (name, stateId, isPopular) values ('Howli', 3, 1);
insert into City (name, stateId, isPopular) values ('Howraghat', 3, 1);
insert into City (name, stateId, isPopular) values ('Jonai', 3, 1);
insert into City (name, stateId, isPopular) values ('Jorhat', 3, 1);
insert into City (name, stateId, isPopular) values ('Kaliabor', 3, 1);
insert into City (name, stateId, isPopular) values ('Kampur', 3, 1);
insert into City (name, stateId, isPopular) values ('Kamrup', 3, 1);
insert into City (name, stateId, isPopular) values ('Karbi ', 3, 1);
insert into City (name, stateId, isPopular) values ('Karimganj', 3, 1);
insert into City (name, stateId, isPopular) values ('Kharupetia', 3, 1);
insert into City (name, stateId, isPopular) values ('Kokrajhar', 3, 1);
insert into City (name, stateId, isPopular) values ('Lakhimpur', 3, 1);
insert into City (name, stateId, isPopular) values ('Lakhipur', 3, 1);
insert into City (name, stateId, isPopular) values ('Lanka', 3, 1);
insert into City (name, stateId, isPopular) values ('Lumding', 3, 1);
insert into City (name, stateId, isPopular) values ('Mahur', 3, 1);
insert into City (name, stateId, isPopular) values ('Maibong', 3, 1);
insert into City (name, stateId, isPopular) values ('Makum', 3, 1);
insert into City (name, stateId, isPopular) values ('Margherita', 3, 1);
insert into City (name, stateId, isPopular) values ('Mariani', 3, 1);
insert into City (name, stateId, isPopular) values ('Moranhat', 3, 1);
insert into City (name, stateId, isPopular) values ('Morigaon', 3, 1);
insert into City (name, stateId, isPopular) values ('Nerkatia', 3, 1);
insert into City (name, stateId, isPopular) values ('Nalbari', 3, 1);
insert into City (name, stateId, isPopular) values ('Namkhola', 3, 1);
insert into City (name, stateId, isPopular) values ('Nazira', 3, 1);
insert into City (name, stateId, isPopular) values ('NorthSalmar', 3, 1);
insert into City (name, stateId, isPopular) values ('Rangapara', 3, 1);
insert into City (name, stateId, isPopular) values ('Roha', 3, 1);
insert into City (name, stateId, isPopular) values ('SadiyaChap', 3, 1);
insert into City (name, stateId, isPopular) values ('SalbariSalb', 3, 1);
insert into City (name, stateId, isPopular) values ('Sapatgram', 3, 1);
insert into City (name, stateId, isPopular) values ('Sarbhog', 3, 1);
insert into City (name, stateId, isPopular) values ('Sarthebari', 3, 1);
insert into City (name, stateId, isPopular) values ('Silapathar', 3, 1);
insert into City (name, stateId, isPopular) values ('Simaluguri', 3, 1);
insert into City (name, stateId, isPopular) values ('Sivasagar', 3, 1);
insert into City (name, stateId, isPopular) values ('sonitpur', 3, 1);
insert into City (name, stateId, isPopular) values ('South Salmar', 3, 1);
insert into City (name, stateId, isPopular) values ('Tamulpur', 3, 1);
insert into City (name, stateId, isPopular) values ('Tihu', 3, 1);
insert into City (name, stateId, isPopular) values ('Tinsukia', 3, 1);
insert into City (name, stateId, isPopular) values ('Titabor', 3, 1);
insert into City (name, stateId, isPopular) values ('Udalguri', 3, 1);
insert into City (name, stateId, isPopular) values ('Umrangsu',3, 1);



-------Bihar----

insert into City (name, stateId, isPopular) values ('Arrah', 4, 1);
insert into City (name, stateId, isPopular) values ('Aurangabad', 4, 1);
insert into City (name, stateId, isPopular) values ('Bagaha', 4, 1);
insert into City (name, stateId, isPopular) values ('Begusarai', 4, 1);
insert into City (name, stateId, isPopular) values ('Bettiah', 4, 1);
insert into City (name, stateId, isPopular) values ('Bhagalpur', 4, 1);
insert into City (name, stateId, isPopular) values ('Buxar', 4, 1);
insert into City (name, stateId, isPopular) values ('Chhapra', 4, 1);
insert into City (name, stateId, isPopular) values ('Darbhanga', 4, 1);
insert into City (name, stateId, isPopular) values ('Dehri', 4, 1);
insert into City (name, stateId, isPopular) values ('Gaya', 4, 1);
insert into City (name, stateId, isPopular) values ('Hajipur', 4, 1);
insert into City (name, stateId, isPopular) values ('Jamalpur', 4, 1);
insert into City (name, stateId, isPopular) values ('Jehanabad', 4, 1);
insert into City (name, stateId, isPopular) values ('Katihar', 4, 1);
insert into City (name, stateId, isPopular) values ('Kishanganj', 4, 1);
insert into City (name, stateId, isPopular) values ('Motihari', 4, 1);
insert into City (name, stateId, isPopular) values ('Munger', 4, 1);
insert into City (name, stateId, isPopular) values ('Muzaffarpur', 4, 1);
insert into City (name, stateId, isPopular) values ('Nawada', 4, 1);
insert into City (name, stateId, isPopular) values ('Patna', 4, 1);
insert into City (name, stateId, isPopular) values ('Purnia',4 , 1);
insert into City (name, stateId, isPopular) values ('Saharsa', 4, 1);
insert into City (name, stateId, isPopular) values ('Sasaram', 4, 1);
insert into City (name, stateId, isPopular) values ('Sitamarhi', 4, 1);
insert into City (name, stateId, isPopular) values ('Siwan', 4, 1);




----chhattisgarsh----

insert into City (name, stateId, isPopular) values ('Ambikapur', 5, 1);
insert into City (name, stateId, isPopular) values ('Bilaspur', 5, 1);
insert into City (name, stateId, isPopular) values ('Bilaspur', 5, 1);
insert into City (name, stateId, isPopular) values ('Dhamtari', 5, 1);
insert into City (name, stateId, isPopular) values ('Durg', 5, 1);
insert into City (name, stateId, isPopular) values ('Jagdalpur', 5, 1);
insert into City (name, stateId, isPopular) values ('Korba', 5, 1);
insert into City (name, stateId, isPopular) values ('Mahasamund', 5, 1);
insert into City (name, stateId, isPopular) values ('Pakhanjore', 5, 1);
insert into City (name, stateId, isPopular) values ('Raigarh', 5, 1);
insert into City (name, stateId, isPopular) values ('Raipur', 5, 1);
insert into City (name, stateId, isPopular) values ('Rajnandgaon', 5, 1);


 -----------G0a-------

insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);
insert into City (name, stateId, isPopular) values ('', 6, 1);



          -------Gujarat------


insert into City (name, stateId, isPopular) values ('Ahmedabad', 7, 1);
insert into City (name, stateId, isPopular) values ('Bhavnagar', 7, 1);
insert into City (name, stateId, isPopular) values ('Gandhidham', 7, 1);
insert into City (name, stateId, isPopular) values ('Gandhidham', 7, 1);
insert into City (name, stateId, isPopular) values ('Jamnagar', 7, 1);
insert into City (name, stateId, isPopular) values ('Junagadh', 7, 1);
insert into City (name, stateId, isPopular) values ('Morvi', 7, 1);
insert into City (name, stateId, isPopular) values ('Nadiad', 7, 1);
insert into City (name, stateId, isPopular) values ('Rajkot', 7, 1);
insert into City (name, stateId, isPopular) values ('Surat', 7, 1);
insert into City (name, stateId, isPopular) values ('Surendranagar', 7, 1);
insert into City (name, stateId, isPopular) values ('Vadodara', 7, 1);

            ----Haryana -----
insert into City (name, stateId, isPopular) values ('Ambala', 8, 1);
insert into City (name, stateId, isPopular) values ('Asandh', 8, 1);
insert into City (name, stateId, isPopular) values ('Ateli', 8, 1);
insert into City (name, stateId, isPopular) values ('Bahadurgarh', 8, 1);
insert into City (name, stateId, isPopular) values ('Barwala', 8, 1);
insert into City (name, stateId, isPopular) values ('Bawal', 8, 1);
insert into City (name, stateId, isPopular) values ('Beri Khas', 8, 1);
insert into City (name, stateId, isPopular) values ('Bhiwani', 8, 1);
insert into City (name, stateId, isPopular) values ('Bilaspur', 8, 1);
insert into City (name, stateId, isPopular) values ('Buriya', 8, 1);
insert into City (name, stateId, isPopular) values ('Charkhi Dadri', 8, 1);
insert into City (name, stateId, isPopular) values ('Chhachhrauli', 8, 1);
insert into City (name, stateId, isPopular) values ('Dabwali', 8, 1);
insert into City (name, stateId, isPopular) values ('Dharuhera', 8, 1);
insert into City (name, stateId, isPopular) values ('Ellenabad', 8, 1);
insert into City (name, stateId, isPopular) values ('Faridabad', 8, 1);
insert into City (name, stateId, isPopular) values ('Farrukhnagar', 8, 1);
insert into City (name, stateId, isPopular) values ('Fatehabad', 8, 1);
insert into City (name, stateId, isPopular) values ('Firozpur Jhirka', 8, 1);
insert into City (name, stateId, isPopular) values ('Gharaunda', 8, 1);
insert into City (name, stateId, isPopular) values ('Gohana', 8, 1);
insert into City (name, stateId, isPopular) values ('Gorakhpur', 8, 1);
insert into City (name, stateId, isPopular) values ('Hansi', 8, 1);
insert into City (name, stateId, isPopular) values ('Hasanpur', 8, 1);
insert into City (name, stateId, isPopular) values ('Hisar', 8, 1);
insert into City (name, stateId, isPopular) values ('Hodal', 8, 1);
insert into City (name, stateId, isPopular) values ('Indri', 8, 1);
insert into City (name, stateId, isPopular) values ('Jagadhri', 8, 1);
insert into City (name, stateId, isPopular) values ('Jakhal', 8, 1);
insert into City (name, stateId, isPopular) values ('Jhajjar', 8, 1);
insert into City (name, stateId, isPopular) values ('Jind', 8, 1);
insert into City (name, stateId, isPopular) values ('Julana Shadipur', 8, 1);
insert into City (name, stateId, isPopular) values ('Kaithal', 8, 1);
insert into City (name, stateId, isPopular) values ('Kalanaur', 8, 1);
insert into City (name, stateId, isPopular) values ('Kalanwali', 8, 1);
insert into City (name, stateId, isPopular) values ('Kalina Khas', 8, 1);
insert into City (name, stateId, isPopular) values ('Karnal', 8, 1);
insert into City (name, stateId, isPopular) values ('Kharkhauda', 8, 1);
insert into City (name, stateId, isPopular) values ('Kheri Sampla', 8, 1);
insert into City (name, stateId, isPopular) values ('Ladwa', 8, 1);
insert into City (name, stateId, isPopular) values ('Loharu', 8, 1);
insert into City (name, stateId, isPopular) values ('Maham', 8, 1);
insert into City (name, stateId, isPopular) values ('Mahendragarh', 8, 1);
insert into City (name, stateId, isPopular) values ('Mandholi Kalan', 8, 1);
insert into City (name, stateId, isPopular) values ('Mustafabad', 8, 1);
insert into City (name, stateId, isPopular) values ('Narnaul', 8, 1);
insert into City (name, stateId, isPopular) values ('Narnaund', 8, 1);
insert into City (name, stateId, isPopular) values ('Narwana', 8, 1);
insert into City (name, stateId, isPopular) values ('Nilokheri', 8, 1);
insert into City (name, stateId, isPopular) values ('Nuh', 8, 1);
insert into City (name, stateId, isPopular) values ('Palwal', 8, 1);
insert into City (name, stateId, isPopular) values ('Panchkula', 8, 1);
insert into City (name, stateId, isPopular) values ('Panipat', 8, 1);
insert into City (name, stateId, isPopular) values ('Pataudi', 8, 1);
insert into City (name, stateId, isPopular) values ('Pehowa', 8, 1);
insert into City (name, stateId, isPopular) values ('Pinjaur', 8, 1);
insert into City (name, stateId, isPopular) values ('Punahana', 8, 1);
insert into City (name, stateId, isPopular) values ('Pundri', 8, 1);
insert into City (name, stateId, isPopular) values ('Radaur', 8, 1);
insert into City (name, stateId, isPopular) values ('Rania', 8, 1);
insert into City (name, stateId, isPopular) values ('Ratia', 8, 1);
insert into City (name, stateId, isPopular) values ('Rewari', 8, 1);
insert into City (name, stateId, isPopular) values ('Rohtak', 8, 1);
insert into City (name, stateId, isPopular) values ('Safidon', 8, 1);
insert into City (name, stateId, isPopular) values ('Samalkha', 8, 1);
insert into City (name, stateId, isPopular) values ('Sangaria', 8, 1);
insert into City (name, stateId, isPopular) values ('Shahabad', 8, 1);
insert into City (name, stateId, isPopular) values ('Sirsa', 8, 1);
insert into City (name, stateId, isPopular) values ('Sohna', 8, 1);
insert into City (name, stateId, isPopular) values ('Sonipat', 8, 1);
insert into City (name, stateId, isPopular) values ('Taoru', 8, 1);
insert into City (name, stateId, isPopular) values ('Thanesar', 8, 1);
insert into City (name, stateId, isPopular) values ('Tohana', 8, 1);
insert into City (name, stateId, isPopular) values ('Tosham', 8, 1);
insert into City (name, stateId, isPopular) values ('Uchana', 8, 1);
insert into City (name, stateId, isPopular) values ('Uklana', 8, 1);
insert into City (name, stateId, isPopular) values ('Yamunanagar', 8, 1);


             ------Kerala-------
insert into City (name, stateId, isPopular) values ('Alappuzha', 13, 1);
insert into City (name, stateId, isPopular) values ('Attingal', 13, 1);
insert into City (name, stateId, isPopular) values ('Beypore', 13, 1);
insert into City (name, stateId, isPopular) values ('Chalakkudy', 13, 1);
insert into City (name, stateId, isPopular) values ('Chavakkad', 13, 1);
insert into City (name, stateId, isPopular) values ('Cherthala', 13, 1);
insert into City (name, stateId, isPopular) values ('Ernakulam', 13, 1);
insert into City (name, stateId, isPopular) values ('Kalamassery', 13, 1);
insert into City (name, stateId, isPopular) values ('Kanhangad', 13, 1);
insert into City (name, stateId, isPopular) values ('Kannur', 13, 1);
insert into City (name, stateId, isPopular) values ('Kasaragod', 13, 1);
insert into City (name, stateId, isPopular) values ('Kattappana', 13, 1);
insert into City (name, stateId, isPopular) values ('Kayamkulam', 13, 1);
insert into City (name, stateId, isPopular) values ('Kochi', 13, 1);
insert into City (name, stateId, isPopular) values ('Kollam', 13, 1);
insert into City (name, stateId, isPopular) values ('Kottakkal', 13, 1);
insert into City (name, stateId, isPopular) values ('Kottayam', 13, 1);
insert into City (name, stateId, isPopular) values ('Koyilandy', 13, 1);
insert into City (name, stateId, isPopular) values ('Kozhikode', 13, 1);
insert into City (name, stateId, isPopular) values ('Kunnamkulam', 13, 1);
insert into City (name, stateId, isPopular) values ('Malappuram', 13, 1);
insert into City (name, stateId, isPopular) values ('Mananthavady', 13, 1);
insert into City (name, stateId, isPopular) values ('Manjeri', 13, 1);
insert into City (name, stateId, isPopular) values ('Manjeshwaram', 13, 1);
insert into City (name, stateId, isPopular) values ('Maradu', 13, 1);
insert into City (name, stateId, isPopular) values ('Mattanur', 13, 1);
insert into City (name, stateId, isPopular) values ('Neyyattinkara', 13, 1);
insert into City (name, stateId, isPopular) values ('Nilambur', 13, 1);
insert into City (name, stateId, isPopular) values ('Nileshwaram', 13, 1);
insert into City (name, stateId, isPopular) values ('Ottappalam', 13, 1);
insert into City (name, stateId, isPopular) values ('Palakkad', 13, 1);
insert into City (name, stateId, isPopular) values ('Pandalam', 13, 1);
insert into City (name, stateId, isPopular) values ('Paravur', 13, 1);
insert into City (name, stateId, isPopular) values ('Pathanamthitta', 13, 1);
insert into City (name, stateId, isPopular) values ('Payyanur', 13, 1);
insert into City (name, stateId, isPopular) values ('Perinthalmanna', 2, 1);
insert into City (name, stateId, isPopular) values ('Ponnani', 13, 1);
insert into City (name, stateId, isPopular) values ('Punalur', 13, 1);
insert into City (name, stateId, isPopular) values ('Ramanattukara', 13, 1);
insert into City (name, stateId, isPopular) values ('Shornur', 13, 1);
insert into City (name, stateId, isPopular) values ('Taliparamba', 13, 1);
insert into City (name, stateId, isPopular) values ('Thalassery', 13, 1);
insert into City (name, stateId, isPopular) values ('Thiruvananthapuram', 13, 1);
insert into City (name, stateId, isPopular) values ('Thodupuzha', 13, 1);
insert into City (name, stateId, isPopular) values ('Thrissur', 13, 1);
insert into City (name, stateId, isPopular) values ('Tirur', 13, 1);
insert into City (name, stateId, isPopular) values ('Tirurangadi', 13, 1);
insert into City (name, stateId, isPopular) values ('Tiruvalla', 13, 1);
insert into City (name, stateId, isPopular) values ('Uppala', 13, 1);
insert into City (name, stateId, isPopular) values ('Vadakara', 13, 1);
insert into City (name, stateId, isPopular) values ('Varkala', 13, 1);
